routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
 */

// Login/Logout Routes
Route::get('/login', 'LoginController@showLogin')->name('admin.login');
Route::post('/login', 'LoginController@doLogin')->name('admin.login');
Route::get('/logout', 'LoginController@doLogout')->name('admin.logout');

Route::group(['middleware' => ['admin']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    // Users Management
    Route::get('users/delete/{user}', 'UserController@delete')->name('users.delete');
    Route::get('users/status/{user}', 'UserController@changeStatus')->name('users.status');
    Route::resource('users', 'UserController');
    //Company management
    Route::get('companies/delete/{id}', 'CompanyController@delete')->name('companies.delete');
    Route::get('companies/users/{id}', 'CompanyController@users')->name('companies.users');
    Route::resource('companies', 'CompanyController');
    //Cases management
    Route::get('cases/', 'CasesController@index')->name('cases.index');
    Route::get('cases/trusted', 'CasesController@trustedCases')->name('cases.trusted');
    Route::get('cases/fake', 'CasesController@fakeCases')->name('cases.fake');
    Route::get('cases/flagcase/{case}', 'CasesController@flagCase')->name('cases.flag');
    Route::get('cases/info/{case}', 'CasesController@caseInfo')->name('cases.info');
    // Settings
    Route::get('/settings', 'SettingController@index')->name('settings');
    Route::post('/settings', 'SettingController@store')->name('settings.store');
    Route::get('/clear-cache', 'SettingController@clearCache')->name('clearcache');

});

routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Front Routes
|--------------------------------------------------------------------------
|
| Here is where you can register front routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "front" middleware group. Now create something great!
|
*/

// Login/Logout Routes
Route::get('/login', 'LoginController@showLogin')->name('login');
Route::post('/login', 'LoginController@doLogin')->name('login');
Route::get('/logout', 'LoginController@doLogout')->name('logout');

Route::group(['prefix' => 'password'], function () {
    // Reset request email
    $this->get('reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.forgot');
    $this->post('email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

    // Reset form
    $this->get('reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('reset', 'ResetPasswordController@reset')->name('password.update');
});


Route::group(['middleware' => ['auth:front', 'front']], function () {
    Route::get('/', 'CasesController@index')->name('cases');

    Route::get('/new', 'CasesController@newCase')->name('newcase');
    Route::post('/new', 'CasesController@storeCase')->name('newcase');

    Route::post('/section-flag/{section}/{case}', 'CasesController@flagCaseBySection')->name('section-flag');
    Route::post('/flag-case/{case}', 'CasesController@flagCase')->name('flag-case');

    Route::get('/info/{case}', 'CasesController@caseInfo')->name('caseinfo');
    Route::get('/analysis/{case}', 'CasesController@postAnalysis')->name('analysis');
    Route::get('/author-posts/{case}', 'CasesController@authorPosts')->name('author-posts');
    Route::get('/post-location/{case}', 'CasesController@geoLocationMap')->name('post-location');
    Route::get('/similar-posts/{case}', 'CasesController@similarPosts')->name('similar-posts');
    Route::get('/samearea-posts/{case}', 'CasesController@sameAreaPosts')->name('samearea-posts');
    Route::get('/author-profile/{case}', 'CasesController@authorProfile')->name('author-profile');
    Route::get('/image-search/{case}', 'CasesController@imageSearch')->name('image-search');
    Route::get('/source-cross-check/{case}', 'CasesController@sourceCrossCheck')->name('source-cross');
    Route::get('/results/{case}', 'CasesController@results')->name('results');
    Route::get('/related/{case}', 'CasesController@relatedCases')->name('related');
    Route::get('/cache/{key}', 'CasesController@clearCache')->name('cache');
    Route::get('/discussions/{case}', 'DiscussionController@discussion')->name('discussions');
    Route::post('/discussions/{case}', 'DiscussionController@discussionSave')->name('discussions');

    Route::get('/edit/{case}', 'CasesController@editCase')->name('editcase');
    Route::post('/edit/{case}', 'CasesController@updateCase')->name('editcase');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Setting;
use App\NewsCase;
use App\User;
use Auth;


class Company extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'companies';


    /**
     * Get users of company.
     */
    public function users()
    {
        return $this->hasMany('App\User');
    }


     /**
    * return full name of user
    *
    * @return string
    */
    public function getCompanyAdminAttribute()
    {
        return $this->users->where('role', User::ROLE_COMPANY_ADMIN)->first();
    }

    /**
    * Get comapny cases by user
    *
    * @param User|int $user
    */
    public function getCompanyCasesOfUser($user)
    {
        if (is_int($user)) {
            $user = User::find($user);
        }

        $companyUsers = $user->company->users()->get()->pluck('id');
        return NewsCase::whereIn('user_id', $companyUsers);
    }

    /**
    * Get comapny cases
    *
    * @param Company $company
    */
    public function getCompanyCases($company)
    {
        $companyUsers = $company->users()->get()->pluck('id');
        return NewsCase::whereIn('user_id', $companyUsers);
    }


    /**
    * return company api details
    *
    * @return array
    */
    public function getCompanyTwitterDetails()
    {
        $currentUser = Auth::user();

        if($currentUser->isCompanyAdmin() || $currentUser->isUser()) {
            $company = $currentUser->company;

            $companyTwitterDetails = [];

            if($company->twitter_consumer_key == '' || $company->twitter_consumer_secret == ''  || $company->twitter_access_token == ''  || $company->twitter_access_token_secret == ''){
                $settings = new Setting;
                $companyTwitterDetails['consumer_key'] = $settings->getSettingValueByKey('twitter_consumer_key');
                $companyTwitterDetails['consumer_secret'] = $settings->getSettingValueByKey('twitter_consumer_secret');
                $companyTwitterDetails['token'] = $settings->getSettingValueByKey('twitter_access_token');
                $companyTwitterDetails['secret'] = $settings->getSettingValueByKey('twitter_access_token_secret');
            } else {
                $companyTwitterDetails['consumer_key'] = $company->twitter_consumer_key;
                $companyTwitterDetails['consumer_secret'] = $company->twitter_consumer_secret;
                $companyTwitterDetails['token'] = $company->twitter_access_token;
                $companyTwitterDetails['secret'] = $company->twitter_access_token_secret;
            }

            return $companyTwitterDetails;
        }

    }

}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Company;
use Hash;
use Auth;
use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Http\Requests\Admin\StoreCompany;
use App\Http\Requests\Admin\updateCompany;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class CompanyController extends Controller
{
    /** @var Company */
    private $company;
    /** @var User */
    private $user;
    private $pagination = 10;

    /**
     * UserController Consturctor
     *
     * @param Company $company
     * @param User $user
     */
    public function __construct(Company $company, User $user)
    {
        $this->company = $company;
        $this->user = $user;

    }

    /**
    * User listing
    *
    * @param Request $request
    * @return Response
    */
    public function index(Request $request)
    {
        $companies = $this->company->paginate(10);

        $grid = new \Datagrid($companies, $request->get('f', []));
        $grid
            ->setColumn('id', 'Id')
            ->setColumn('name', 'Name',[
                    'wrapper'     => function ($value, $row) {
                        return '<a href="' .route('companies.show', $row->id). '">' . $value . '</a>';
                    }
            ])
            ->setColumn('website', 'Website')
            ->setColumn('phone', 'Phone')
            ->setColumn('companyAdmin', 'Admin', [
                    'refers_to'   => 'companyAdmin.name'
            ])
            ->setColumn('created_at', 'Created At')
            ->setColumn('updated_at', 'Updated At')
            ->setActionColumn([
                'wrapper' => function ($value, $row) {
                    return '
                        <a href="'.route("companies.users", $row->id).'" title="View Company Users" class="btn btn-xs"><i class="fa fa-users" aria-hidden="true"></i></a>
                        <a href="'.route("companies.edit", $row->id).'" title="Edit" class="btn btn-xs"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                         <a href="'.route("companies.delete", $row->id).'" title="Delete" data-method="DELETE" class="btn btn-xs text-danger delete_confirm" ><i class="fa fa-remove" aria-hidden="true"></i></a>
                        ';
                }
            ]);

        return view('Admin.companies.index', ['grid' => $grid]);
    }

    /**
    * Show the form for creating a new user.
    *
    * @return Response
    */
    public function create()
    {
        $users = User::where('role', User::ROLE_COMPANY_ADMIN)->whereNull('company_id')->get()->pluck('name', 'id');
        return view('Admin.companies.create', ['users' => $users]);
    }

    /**
    * Store user in database
    *
    * @param StoreUser $request
    * @return Response
    */
    public function store(StoreCompany $request)
    {

        $this->company->name = $request->get('name');
        $this->company->website = $request->get('website');
        $this->company->phone = $request->get('phone');
        $this->company->address = $request->get('address');
        $this->company->twitter_consumer_key = $request->get('twitter_consumer_key');
        $this->company->twitter_consumer_secret = $request->get('twitter_consumer_secret');
        $this->company->twitter_access_token = $request->get('twitter_access_token');
        $this->company->twitter_access_token_secret = $request->get('twitter_access_token_secret');

        $this->company->save();

        // Assign admin to company
        if($request->filled('admin')) {
            $user = $this->user->find($request->get('admin'));
            $this->company->users()->save($user);
        }

        return redirect(route('companies.index'))
            ->with('success','Company created successfully!');
    }

    /**
    * Show the company data
    *
    * @return Response
    */
    public function show($id)
    {
        $details = $this->company->getCompanyTwitterDetails($id);

        $company =  $this->company->findorFail($id);
        return view('Admin.companies.show', ['company' => $company]);
    }

    /**
    * Show the form for edit a company.
    *
    * @return Response
    */
    public function edit($id)
    {
        $company =  $this->company->findorFail($id);
        $users = User::where('role', User::ROLE_COMPANY_ADMIN)
                        ->where(function ($query) use ($id) {
                                $query->whereNull('company_id')
                                      ->orWhere('company_id', $id);
                            })
                        ->get()->pluck('name', 'id');
        return view('Admin.companies.edit', ['company' => $company, 'users' => $users]);
    }

    /**
    * Store company in database
    *
    * @param updateCompany $request
    * @param int $id
    * @return Response
    */
    public function update(updateCompany $request, $id)
    {
        $company = $this->company->findorFail($id);

        $company->name = $request->get('name');
        $company->website = $request->get('website');
        $company->phone = $request->get('phone');
        $company->address = $request->get('address');
        $company->twitter_consumer_key = $request->get('twitter_consumer_key');
        $company->twitter_consumer_secret = $request->get('twitter_consumer_secret');
        $company->twitter_access_token = $request->get('twitter_access_token');
        $company->twitter_access_token_secret = $request->get('twitter_access_token_secret');

        $company->save();

        // Assign admin to company
        if($request->filled('admin')) {
            // Remove old company admin
            if (is_object($company->companyAdmin)) {
                $oldUser = $this->user->find($company->companyAdmin->id);
                $oldUser->company()->dissociate($company);
                $oldUser->save();
            }

            $user = $this->user->find($request->get('admin'));
            $company->users()->save($user);

        }

        if( Auth::user()->isCompanyAdmin()) {
            return redirect()->back()->with('success','Company updated successfully!');
        }

        return redirect(route('companies.index'))
                ->with('success','Company updated successfully!');
    }

    /**
    * Delete Company
    *
    * @param int $id
    * @return Response
    */
    public function delete($id)
    {

        $company = $this->company->findorFail($id);
        $company->delete();

        return redirect(route('companies.index'))
            ->with('success','Company deleted successfully!');
    }

    /**
    * Company Users
    *
    * @param int $id
    * @return Response
    */
    public function users(Request $request, $id){
        $company = $this->company->findorFail($id);

        $users = $company->users()->paginate($this->pagination);

        $grid = new \Datagrid($users, $request->get('f', []));
        $grid
            ->setColumn('id', 'Id')
            ->setColumn('name', 'Name', [
                    'wrapper'     => function ($value, $row) {
                        return '<a href="' .route('users.show', $row->id). '">' . $value . '</a>';
                    }
            ])
            ->setColumn('email', 'Email', [
                'wrapper'     => function ($value, $row) {
                    return '<a href="mailto:' . $value . '">' . $value . '</a>';
                },
            ])
            ->setColumn('roleName', 'Role')
            ->setColumn('created_at', 'Created At')
            ->setColumn('updated_at', 'Updated At')
            ->setActionColumn([
                'wrapper' => function ($value, $row) {
                    if($row->status == 1) {
                        $actions = '<a href="'.route("users.status", $row->id).'" data-tooltip="Disable User" class="btn btn-xs"><span class="glyphicon glyphicon-check text-danger" aria-hidden="true"></span></a>';
                    } else {
                        $actions = '<a href="'.route("users.status", $row->id).'" data-tooltip="Enable User" class="btn btn-xs"><span class="glyphicon glyphicon-check" aria-hidden="true"></span></a>';
                    }

                    $actions .= '<a href="'.route("users.edit", $row->id).'" data-tooltip="Edit" class="btn btn-xs"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            <a href="'.route("users.delete", $row->id).'" data-tooltip="Delete" data-method="DELETE" class="btn btn-xs text-danger delete_confirm" ><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>';

                    return $actions;
                }
            ]);

        return view('Admin.companies.users', ['company' => $company, 'grid' => $grid]);

    }

    public function autocomplete(Request $request){

        $query = $request->get('query','');

        $companies = Company::where('name','LIKE','%'.$query.'%')->get();

        return response()->json($companies);
    }

}

resources/views/Admin/companies/company-info.blade.php
 @if (isset($company))
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">{{ $title }}</h3>
            </div>
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>Name:</dt>
                    <dd>{{{ $company->name }}}</dd>

                    <dt>Website:</dt>
                    <dd>{{{ $company->website }}}</dd>

                    <dt>Phone:</dt>
                    <dd>{{{ $company->phone }}}</dd>

                    <dt>Address:</dt>
                    <dd>{{{ $company->address }}}</dd>

                    <dt>Twitter Consumer Key:</dt>
                    <dd>{{{ $company->twitter_consumer_key }}}</dd>

                    <dt>Twitter Consumer Secret:</dt>
                    <dd>{{{ $company->twitter_consumer_secret }}}</dd>

                    <dt>Twitter Access Token:</dt>
                    <dd>{{{ $company->twitter_access_token }}}</dd>

                    <dt>Twitter Access Token Secret:</dt>
                    <dd>{{{ $company->twitter_access_token_secret }}}</dd>

                </dl>
                @if (!Auth::user()->isCompanyAdmin())
                     <a href="{{ route('companies.index') }}" title="Back to company list" class="btn btn-sm btn-warning pull-left">
                        <i class="glyphicon glyphicon-fast-backward"></i>
                         Back
                    </a>
                    <a href="{{ route('companies.edit', $company->id) }}" title="Edit User" class="btn btn-sm btn-primary pull-right">
                        <i class="glyphicon glyphicon-pencil"></i>
                         Edit Company
                    </a>
                @endif
            </div>
        </div>
    </div>
@endif

resources/views/Admin/companies/create.blade.php
@extends('layouts.admin')

@section('title', 'Add Company')
@section('page-header', 'Add Company')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Company Info</h3>
                    <a href="{{ route('companies.index') }}" title="Back" class="btn btn-sm btn-primary pull-right">
                        <i class="glyphicon glyphicon-fast-backward"></i>
                         Back
                    </a>
                </div>
                {{ Form::open(['url'=> route('companies.store')]) }}
                    <div class="box-body">
                        <div class="form-group {{ $errors->first('name')?'has-error':'' }}">
                            {{ Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Name']) }}
                            <span class="help-block">{{ $errors->first('name') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('website')?'has-error':'' }}">
                            {{ Form::text('website', '', ['class' => 'form-control', 'placeholder' => 'Website']) }}
                            <span class="help-block">{{ $errors->first('website') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('phone')?'has-error':'' }}">
                            {{ Form::text('phone', '', ['class' => 'form-control', 'placeholder' => 'Phone']) }}
                            <span class="help-block">{{ $errors->first('phone') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('address')?'has-error':'' }}">
                            {{ Form::text('address', '', ['class' => 'form-control', 'placeholder' => 'Address']) }}
                            <span class="help-block">{{ $errors->first('address') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('admin')?'has-error':'' }}">
                            {{ Form::select('admin', $users, null, ['class' => 'form-control select2', 'placeholder' => 'Choose company admin']) }}
                            <span class="help-block">{{ $errors->first('admin') }}</span>
                        </div>
                        <div class="form-group has-warning">
                               <span class="help-block"><i class="glyphicon glyphicon-question-sign"></i> If company admin is not available please <a href="{{ route('users.create')}}" title="Create User"> create new user</a></span>
                        </div>
                        <div class="box-header with-border">
                            <h3 class="box-title">Twitter API Details</h3>
                        </div>
                        <div class="form-group {{ $errors->first('twitter_consumer_key')?'has-error':'' }}">
                            {{ Form::text('twitter_consumer_key', '', ['class' => 'form-control', 'placeholder' => 'Twitter Consumer Key']) }}
                            <span class="help-block">{{ $errors->first('twitter_consumer_key') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('twitter_consumer_secret')?'has-error':'' }}">
                            {{ Form::text('twitter_consumer_secret', '', ['class' => 'form-control', 'placeholder' => 'Twitter Consumer Secret']) }}
                            <span class="help-block">{{ $errors->first('twitter_consumer_secret') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('twitter_access_token')?'has-error':'' }}">
                            {{ Form::text('twitter_access_token', '', ['class' => 'form-control', 'placeholder' => 'Twitter Access Token']) }}
                            <span class="help-block">{{ $errors->first('twitter_access_token') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('twitter_access_token_secret')?'has-error':'' }}">
                            {{ Form::text('twitter_access_token_secret', '', ['class' => 'form-control', 'placeholder' => 'Twitter Access Token Secret']) }}
                            <span class="help-block">{{ $errors->first('twitter_access_token_secret') }}</span>
                        </div>
                        <div class="box-footer">
                            {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}
                        </div>
                    </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/companies/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Company')
@section('page-header', 'Edit Company')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Company Info</h3>
                    @if(!Auth::user()->isCompanyAdmin())
                        <a href="{{ route('companies.index') }}" title="Back" class="btn btn-sm btn-primary pull-right">
                            <i class="glyphicon glyphicon-fast-backward"></i>
                             Back
                        </a>
                    @endif
                </div>
                 {{ Form::model($company, ['url'=> route('companies.update', $company->id), 'method' => 'PUT']) }}
                    <div class="box-body">
                        <div class="form-group {{ $errors->first('name')?'has-error':'' }}">
                            {{ Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Name']) }}
                            <span class="help-block">{{ $errors->first('name') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('website')?'has-error':'' }}">
                            {{ Form::text('website', null, ['class' => 'form-control', 'placeholder' => 'Website']) }}
                            <span class="help-block">{{ $errors->first('website') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('phone')?'has-error':'' }}">
                            {{ Form::text('phone', null, ['class' => 'form-control', 'placeholder' => 'Phone']) }}
                            <span class="help-block">{{ $errors->first('phone') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('address')?'has-error':'' }}">
                            {{ Form::text('address', null, ['class' => 'form-control', 'placeholder' => 'Address']) }}
                            <span class="help-block">{{ $errors->first('address') }}</span>
                        </div>
                        @if(!Auth::user()->isCompanyAdmin())
                             <div class="form-group {{ $errors->first('admin')?'has-error':'' }}">
                                {{ Form::select('admin', $users, isset($company->companyAdmin->id) ? $company->companyAdmin->id : null, ['class' => 'form-control select2', 'placeholder' => 'Choose company admin']) }}
                                <span class="help-block">{{ $errors->first('admin') }}</span>
                            </div>
                             <div class="form-group has-warning">
                                   <span class="help-block"><i class="glyphicon glyphicon-question-sign"></i> If company admin is not available please <a href="{{ route('users.create')}}" title="Create User"> create new user</a></span>
                            </div>
                        @endif

                        <div class="box-header with-border">
                            <h3 class="box-title">Twitter API Details</h3>
                        </div>
                        <div class="form-group {{ $errors->first('twitter_consumer_key')?'has-error':'' }}">
                            {{ Form::text('twitter_consumer_key', null, ['class' => 'form-control', 'placeholder' => 'Twitter Consumer Key']) }}
                            <span class="help-block">{{ $errors->first('twitter_consumer_key') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('twitter_consumer_secret')?'has-error':'' }}">
                            {{ Form::text('twitter_consumer_secret', null, ['class' => 'form-control', 'placeholder' => 'Twitter Consumer Secret']) }}
                            <span class="help-block">{{ $errors->first('twitter_consumer_secret') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('twitter_access_token')?'has-error':'' }}">
                            {{ Form::text('twitter_access_token', null, ['class' => 'form-control', 'placeholder' => 'Twitter Access Token']) }}
                            <span class="help-block">{{ $errors->first('twitter_access_token') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('twitter_access_token_secret')?'has-error':'' }}">
                            {{ Form::text('twitter_access_token_secret', null, ['class' => 'form-control', 'placeholder' => 'Twitter Access Token Secret']) }}
                            <span class="help-block">{{ $errors->first('twitter_access_token_secret') }}</span>
                        </div>
                        <div class="box-footer">
                            {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}
                        </div>
                    </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/companies/index.blade.php
@extends('layouts.admin')

@section('title', 'Companies')
@section('page-header', 'Companies')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border col-md-3 pull-right">
                  <a href="{{ route('companies.create') }}" class="btn btn-block btn-primary">Add New Company</a>
                </div>
                {!! $grid->show('grid-table') !!}
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/companies/show.blade.php
@extends('layouts.admin')

@section('title', 'Company Info')
@section('page-header', 'Company Info')

@section('content')
    <div class="row">
        @include('Admin.companies.company-info', ['title' => 'Admin Info', 'user' => $company->companyAdmin])
        @include('Admin.users.user-info', ['title' => 'Admin Info', 'user' => $company->companyAdmin])
    </div>
@endsection

resources/views/Admin/companies/users.blade.php
@extends('layouts.admin')

@section('title', $company->name .' Users')
@section('page-header', $company->name .' Users')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border col-md-3 pull-right">
                  <a href="{{ route('users.create', ['company' => $company->id]) }}" class="btn btn-block btn-primary">Add New User</a>
                </div>
                {!! $grid->show('grid-table') !!}
            </div>
        </div>
    </div>
@endsection