routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
 */

// Login/Logout Routes
Route::get('/login', 'LoginController@showLogin')->name('admin.login');
Route::post('/login', 'LoginController@doLogin')->name('admin.login');
Route::get('/logout', 'LoginController@doLogout')->name('admin.logout');

Route::group(['middleware' => ['admin']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    // Users Management
    Route::get('users/delete/{user}', 'UserController@delete')->name('users.delete');
    Route::get('users/status/{user}', 'UserController@changeStatus')->name('users.status');
    Route::resource('users', 'UserController');
    //Company management
    Route::get('companies/delete/{id}', 'CompanyController@delete')->name('companies.delete');
    Route::get('companies/users/{id}', 'CompanyController@users')->name('companies.users');
    Route::resource('companies', 'CompanyController');
    //Cases management
    Route::get('cases/', 'CasesController@index')->name('cases.index');
    Route::get('cases/trusted', 'CasesController@trustedCases')->name('cases.trusted');
    Route::get('cases/fake', 'CasesController@fakeCases')->name('cases.fake');
    Route::get('cases/flagcase/{case}', 'CasesController@flagCase')->name('cases.flag');
    Route::get('cases/info/{case}', 'CasesController@caseInfo')->name('cases.info');
    // Settings
    Route::get('/settings', 'SettingController@index')->name('settings');
    Route::post('/settings', 'SettingController@store')->name('settings.store');
    Route::get('/clear-cache', 'SettingController@clearCache')->name('clearcache');

});

routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Front Routes
|--------------------------------------------------------------------------
|
| Here is where you can register front routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "front" middleware group. Now create something great!
|
*/

// Login/Logout Routes
Route::get('/login', 'LoginController@showLogin')->name('login');
Route::post('/login', 'LoginController@doLogin')->name('login');
Route::get('/logout', 'LoginController@doLogout')->name('logout');

Route::group(['prefix' => 'password'], function () {
    // Reset request email
    $this->get('reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.forgot');
    $this->post('email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

    // Reset form
    $this->get('reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('reset', 'ResetPasswordController@reset')->name('password.update');
});


Route::group(['middleware' => ['auth:front', 'front']], function () {
    Route::get('/', 'CasesController@index')->name('cases');

    Route::get('/new', 'CasesController@newCase')->name('newcase');
    Route::post('/new', 'CasesController@storeCase')->name('newcase');

    Route::post('/section-flag/{section}/{case}', 'CasesController@flagCaseBySection')->name('section-flag');
    Route::post('/flag-case/{case}', 'CasesController@flagCase')->name('flag-case');

    Route::get('/info/{case}', 'CasesController@caseInfo')->name('caseinfo');
    Route::get('/analysis/{case}', 'CasesController@postAnalysis')->name('analysis');
    Route::get('/author-posts/{case}', 'CasesController@authorPosts')->name('author-posts');
    Route::get('/post-location/{case}', 'CasesController@geoLocationMap')->name('post-location');
    Route::get('/similar-posts/{case}', 'CasesController@similarPosts')->name('similar-posts');
    Route::get('/samearea-posts/{case}', 'CasesController@sameAreaPosts')->name('samearea-posts');
    Route::get('/author-profile/{case}', 'CasesController@authorProfile')->name('author-profile');
    Route::get('/image-search/{case}', 'CasesController@imageSearch')->name('image-search');
    Route::get('/source-cross-check/{case}', 'CasesController@sourceCrossCheck')->name('source-cross');
    Route::get('/results/{case}', 'CasesController@results')->name('results');
    Route::get('/related/{case}', 'CasesController@relatedCases')->name('related');
    Route::get('/cache/{key}', 'CasesController@clearCache')->name('cache');
    Route::get('/discussions/{case}', 'DiscussionController@discussion')->name('discussions');
    Route::post('/discussions/{case}', 'DiscussionController@discussionSave')->name('discussions');

    Route::get('/edit/{case}', 'CasesController@editCase')->name('editcase');
    Route::post('/edit/{case}', 'CasesController@updateCase')->name('editcase');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/User.php
<?php

namespace App;

use App\Company;
use App\Notifications\MailResetPasswordToken;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Aginev\SearchFilters\Filterable;
use Illuminate\Http\Request;
use ReflectionClass;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
    use Notifiable;

    const ROLE_ADMIN = 'admin';
    const ROLE_COMPANY_ADMIN = 'company_admin';
    const ROLE_USER = 'user';
    const DEFAULT_ROLE = 'user';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new MailResetPasswordToken($token));
    }

    /**
     * Get the company that owns the user.
     */
    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    /**
    * Get cases of user.
    */
    public function cases()
    {
        return $this->hasMany('App\NewsCase');
    }

    /**
     * To check role of Admin
     *
     * @return boolean
     */
    public function isAdmin()
    {
        if ($this->role == self::ROLE_ADMIN) {
            return true;
        }

        return false;
    }

    /**
     * To check role of Admin
     *
     * @return boolean
     */
    public function isCompanyAdmin()
    {
        if ($this->role == self::ROLE_COMPANY_ADMIN) {
            return true;
        }

        return false;
    }

    /**
     * To check role of Admin
     *
     * @return boolean
     */
    public function isUser()
    {
        if ($this->role == self::ROLE_USER) {
            return true;
        }

        return false;
    }

    /**
     * To check permission
     *
     * @param Request $request
     * @return boolean
     */
    public function hasPermissionToAction($request)
    {
        if($request->route('user')) {
            $user = User::find($this->id);
            $userCount = $user->company->users()->where('id', $request->route('user'))->count();

            if ($userCount > 0){
                return true;
            }

            return false;
        }

        if($request->route('company')) {
            $user = User::find($this->id);
            if($user->company->id == $request->route('company')){
                return true;
            }

            return false;
        }

        if($request->route('case')) {
            $user = User::find($this->id);
            $companyCases = $user->company->getCompanyCases($user->company)->get()->pluck('id')->toArray();

            if (in_array($request->route('case'), $companyCases)){
                return true;
            }

            return false;
        }


        return true;

    }

    /**
    * return full name of user
    *
    * @return string
    */
    public function getNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

     /**
    * return role of user
    *
    * @return string
    */
    public function getRoleNameAttribute()
    {
        return ucwords(strtolower(str_replace('_', ' ', $this->role)));
    }

    /**
     * Get Roles types as array
     *
     * @return array
     */
    public function getRolesAsArray()
    {
        $prefix = 'ROLE_';
        $reflection = new ReflectionClass(self::class);
        $constants  = $reflection->getConstants();

        $prefixLength = strlen($prefix);
        $options      = [];
        foreach ($constants as $name => $value) {
            if (substr($name, 0, $prefixLength) === $prefix) {
                $enumOptionName = ucwords(strtolower(str_replace('_', ' ', substr($name, $prefixLength))));
                $options[$value] = $enumOptionName;
            }
        }

        return $options;
    }

    /**
     * Get Users as array
     *
     * @param string $role
     * @return array
     */
    public function userListByRole($role){
        return User::where('role', $role)->get()->pluck('name', 'id');
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Company;
use Hash;
use Auth;
use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Http\Requests\Admin\StoreUser;
use App\Http\Requests\Admin\updateUser;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class UserController extends Controller
{
    /** @var User */
    private $user;

    /** @var Company */
    private $company;

    private $pagination = 10;

    /**
     * UserController Consturctor
     *
     * @param User $user
     * @param Company $company
     */
    public function __construct(User $user, Company $company)
    {
        $this->user = $user;
        $this->company = $company;
    }

    /**
    * User listing
    *
    * @param Request $request
    * @return Response
    */
    public function index(Request $request)
    {
        if( Auth::user()->isCompanyAdmin()) {
            $users = Auth::user()->company->users()->paginate($this->pagination);
        } else {
            $users = $this->user->paginate($this->pagination);
        }
        // $users = $this->user->paginate(10);
        $grid = new \Datagrid($users, $request->get('f', []));
        $grid
            ->setColumn('id', 'Id')
            ->setColumn('name', 'Name', [
                    'wrapper'     => function ($value, $row) {
                        return '<a href="' .route('users.show', $row->id). '">' . $value . '</a>';
                    }
            ])
            ->setColumn('email', 'Email', [
                'wrapper'     => function ($value, $row) {
                    return '<a href="mailto:' . $value . '">' . $value . '</a>';
                },
            ])
            ->setColumn('roleName', 'Role')
            ->setColumn('created_at', 'Created At')
            ->setColumn('updated_at', 'Updated At')
            ->setActionColumn([
                'wrapper' => function ($value, $row) {
                    if($row->status == 1) {
                        $actions = '<a href="'.route("users.status", $row->id).'" data-tooltip="Disable User" class="btn btn-xs"><span class="glyphicon glyphicon-check text-danger" aria-hidden="true"></span></a>';
                    } else {
                        $actions = '<a href="'.route("users.status", $row->id).'" data-tooltip="Enable User" class="btn btn-xs"><span class="glyphicon glyphicon-check" aria-hidden="true"></span></a>';
                    }

                    $actions .= '<a href="'.route("users.edit", $row->id).'" data-tooltip="Edit" class="btn btn-xs"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            <a href="'.route("users.delete", $row->id).'" data-tooltip="Delete" data-method="DELETE" class="btn btn-xs text-danger delete_confirm" ><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>';

                    return $actions;
                }
            ]);

        return view('Admin.users.index', ['grid' => $grid]);
    }

    /**
    * Show the form for creating a new user.
    *
    * @return Response
    */
    public function create(Request $request)
    {
        $defaultCompany = null;
        $defaultRole = null;
        if($request->has('company')) {
            $defaultCompany = $request->get('company');
            $defaultRole = User::ROLE_USER;
        }
        $roles =  $this->user->getRolesAsArray();
        $companies = $this->company->pluck('name', 'id');
        return view('Admin.users.create', [
            'roles' => $roles,
            'companies' => $companies,
            'defaultCompany' => $defaultCompany,
            'defaultRole' => $defaultRole
        ]);
    }

    /**
    * Store user in database
    *
    * @param StoreUser $request
    * @return Response
    */
    public function store(StoreUser $request)
    {
        $this->user->first_name = $request->get('first_name');
        $this->user->last_name = $request->get('last_name');
        $this->user->email = $request->get('email');
        $this->user->role = $request->get('role');
        $this->user->password = Hash::make($request->get('password'));

        // Assign company to user
        if($request->filled('company') && $request->get('role') == User::ROLE_USER) {
            $company = $this->company->find($request->get('company'));
            $this->user->company()->associate($company);
        }

        $this->user->save();

        return redirect(route('users.index'))
            ->with('success','User created successfully!');
    }

    /**
    * Show the user data.
    *
    * @return Response
    */
    public function show($id)
    {
        $user =  $this->user->findorFail($id);
        return view('Admin.users.show', ['user' => $user]);
    }

    /**
    * Show the form for edit a user.
    *
    * @return Response
    */
    public function edit($id)
    {
        $user =  $this->user->findorFail($id);
        $roles =  $this->user->getRolesAsArray();
        $companies = $this->company->pluck('name', 'id');
        return view('Admin.users.edit', ['user' => $user, 'roles' => $roles, 'companies' => $companies]);
    }

    /**
    * Store user in database
    *
    * @param updateUser $request
    * @param int $id
    * @return Response
    */
    public function update(updateUser $request, $id)
    {
        $user = $this->user->findorFail($id);
        $user->first_name = $request->get('first_name');
        $user->last_name = $request->get('last_name');
        $user->email = $request->get('email');
        $user->role = $request->get('role');
        if ($request->get('password') !== null) {
            $user->password = Hash::make($request->get('password'));
        }

        // Assign company to user
        if($request->filled('company')) {
            $company = $this->company->find($request->get('company'));
            $user->company()->associate($company);
        }

        $user->save();

        return redirect(route('users.index'))
            ->with('success','User updated successfully!');
    }

    /**
    * Update User status
    *
    * @param int $id
    * @return Response
    */
    public function changeStatus($id)
    {
        $user = $this->user->findorFail($id);
        $status = $user->status === '1' ? '0' : '1';
        $user->status = $status;
        $user->save();

        return redirect()->back()->with('success','User Status has been changed!');
    }

    /**
    * Delete User
    *
    * @param int $id
    * @return Response
    */
    public function delete($id)
    {
        $user = $this->user->findorFail($id);
        $user->delete();

        return redirect(route('users.index'))
            ->with('success','User deleted successfully!');
    }
}

resources/views/Admin/users/create.blade.php
@extends('layouts.admin')

@section('title', 'Add User')
@section('page-header', 'Add User')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">User Info</h3>
                    <a href="{{ route('users.index') }}" title="Back" class="btn btn-sm btn-primary pull-right">
                        <i class="glyphicon glyphicon-fast-backward"></i>
                         Back
                    </a>
                </div>
                {{ Form::open(['url'=> route('users.store')]) }}
                    <div class="box-body">
                        <div class="form-group {{ $errors->first('first_name')?'has-error':'' }}">
                            {{ Form::text('first_name', null, ['class' => 'form-control', 'placeholder' => 'First Name']) }}
                            <span class="help-block">{{ $errors->first('first_name') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('last_name')?'has-error':'' }}">
                            {{ Form::text('last_name', '', ['class' => 'form-control', 'placeholder' => 'Last Name']) }}
                            <span class="help-block">{{ $errors->first('last_name') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('email')?'has-error':'' }}">
                            {{ Form::email('email', '', ['class' => 'form-control', 'placeholder' => 'Email']) }}
                            <span class="help-block">{{ $errors->first('email') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('role')?'has-error':'' }}">
                            {{ Form::select('role', $roles, $defaultRole, ['class' => Auth::user()->isCompanyAdmin() ? 'form-control select2 readonly':'form-control select2', 'placeholder' => 'Role', 'readonly' => true]) }}
                            <span class="help-block">{{ $errors->first('role') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('password')?'has-error':'' }}">
                            {{ Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password']) }}
                            <span class="help-block">{{ $errors->first('password') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('password_confirmation')?'has-error':'' }}">
                            {{ Form::password('password_confirmation', ['class' => 'form-control', 'placeholder' => 'Confirm Password']) }}
                            <span class="help-block">{{ $errors->first('password_confirmation') }}</span>
                        </div>
                        <div class="form-group has-warning" id="user_companies" style="display: none;">
                            {{ Form::select('company', $companies, $defaultCompany, ['class' => Auth::user()->isCompanyAdmin() ? 'form-control select2 readonly':'form-control select2', 'placeholder' => 'Company']) }}
                            <span class="help-block"><i class="glyphicon glyphicon-question-sign"></i> Leave blank if you don't want to assign company.</span>
                        </div>
                        <div class="box-footer">
                            {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}
                        </div>
                    </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/users/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit User')
@section('page-header', 'Edit User')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">User Info</h3>
                    <a href="{{ route('users.index') }}" title="Back" class="btn btn-sm btn-primary pull-right">
                        <i class="glyphicon glyphicon-fast-backward"></i>
                         Back
                    </a>
                </div>
                 {{ Form::model($user, ['url'=> route('users.update', $user->id), 'method' => 'PUT']) }}
                    <div class="box-body">
                        <div class="form-group {{ $errors->first('first_name')?'has-error':'' }}">
                            {{ Form::text('first_name', null, ['class' => 'form-control', 'placeholder' => 'First Name']) }}
                            <span class="help-block">{{ $errors->first('first_name') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('last_name')?'has-error':'' }}">
                            {{ Form::text('last_name', null, ['class' => 'form-control', 'placeholder' => 'Last Name']) }}
                            <span class="help-block">{{ $errors->first('last_name') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('email')?'has-error':'' }}">
                            {{ Form::email('email', null, ['class' => 'form-control', 'placeholder' => 'Email']) }}
                            <span class="help-block">{{ $errors->first('email') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('role')?'has-error':'' }}">
                            {{ Form::select('role', $roles, null, ['class' =>  Auth::user()->isCompanyAdmin() ? 'form-control select2 readonly':'form-control select2', 'placeholder' => 'Role']) }}
                            <span class="help-block">{{ $errors->first('role') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('password')?'has-error':'has-warning' }}">
                            {{ Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password']) }}
                            @if ($errors->first('password'))
                                <span class="help-block">{{ $errors->first('password') }}</span>
                            @else
                                <span class="help-block"><i class="glyphicon glyphicon-question-sign"></i> Leave blank if you don't want to change password.</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->first('password_confirmation')?'has-error':'' }}">
                            {{ Form::password('password_confirmation', ['class' => 'form-control', 'placeholder' => 'Confirm Password']) }}
                            <span class="help-block">{{ $errors->first('password_confirmation') }}</span>
                        </div>
                        <div class="form-group has-warning" id="user_companies" style="display: none;">
                            {{ Form::select('company', $companies, isset($user->company) ?$user->company->id: null, ['class' =>  Auth::user()->isCompanyAdmin() ? 'form-control select2 readonly':'form-control select2', 'placeholder' => 'Company']) }}
                            <span class="help-block"><i class="glyphicon glyphicon-question-sign"></i> Leave blank if you don't want to assign company.</span>
                        </div>
                        <div class="box-footer">
                            {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}
                        </div>
                    </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/users/index.blade.php
@extends('layouts.admin')

@section('title', 'User Listing')
@section('page-header', 'User Listing')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border col-md-3 pull-right">
                  <a href="{{ route('users.create', Auth::user()->isCompanyAdmin()? ['company' => Auth::user()->company->id]:'') }}" class="btn btn-block btn-primary">Add New User</a>
                </div>
                {!! $grid->show('grid-table') !!}
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/users/show.blade.php
@extends('layouts.admin')

@section('title', 'User Info')
@section('page-header', 'User Info')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">User Info</h3>
                </div>
                    @if (isset($user))
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>First Name:</dt>
                                <dd>{{ $user->first_name }}</dd>

                                <dt>Last Name:</dt>
                                <dd>{{ $user->last_name }}</dd>

                                <dt>Email:</dt>
                                <dd>{{ $user->email }}</dd>

                                <dt>Role:</dt>
                                <dd>{{ $user->roleName }}</dd>

                            </dl>
                            <a href="{{ route('users.index') }}" title="Back to User list" class="btn btn-sm btn-warning pull-left">
                                <i class="glyphicon glyphicon-fast-backward"></i>
                                 Back
                            </a>
                            <a href="{{ route('users.edit', $user->id) }}" title="Edit User" class="btn btn-sm btn-primary pull-right">
                                <i class="glyphicon glyphicon-pencil"></i>
                                 Edit User
                            </a>
                        </div>
                    @endif
            </div>
        </div>
        @include('Admin.companies.company-info', ['title' => 'Company Info', 'company' => $user->company])
    </div>
@endsection

resources/views/Admin/users/user-info.blade.php
@if (isset($user))
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">{{ $title }}</h3>
            </div>
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>First Name:</dt>
                    <dd>{{ $user->first_name }}</dd>

                    <dt>Last Name:</dt>
                    <dd>{{ $user->last_name }}</dd>

                    <dt>Email:</dt>
                    <dd>{{ $user->email }}</dd>

                    <dt>Role:</dt>
                    <dd>{{ $user->roleName }}</dd>

                </dl>
                <a href="{{ route('users.index') }}" title="Back to User list" class="btn btn-sm btn-warning pull-left">
                    <i class="glyphicon glyphicon-fast-backward"></i>
                     Back
                </a>
                <a href="{{ route('users.edit', $user->id) }}" title="Edit User" class="btn btn-sm btn-primary pull-right">
                    <i class="glyphicon glyphicon-pencil"></i>
                     Edit User
                </a>
            </div>
        </div>
    </div>
@endif